version: "3.9"
networks:
  back-network:
    driver: bridge

services:
  frontend:
    build:
      context: ../Shhootout-Web/ 
      dockerfile: ../Shhootout-Web/Dockerfile
    environment:
      - FLASK_APP=main
    expose:
      - "5000"
    networks:
      - back-network
    depends_on:
      - "api"
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    expose: 
      - "8000"
    volumes: 
      - ./api:/home/node/app:Z
      - ./api/node_modules:/home/node/app/node_modules:Z
    networks:
      - back-network
    depends_on: 
      - "db"
  db:
    image: mysql:8-oracle
    restart: always
    volumes:
      - "./sql/init:/docker-entrypoint-initdb.d:Z,ro"
    env_file:
      - sql.env
    networks:
      - back-network
    expose:
      - "3306"
  rproxy:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/proxy.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/ssl/:/ssl/:ro
    networks:
      - back-network

