runtime: python39

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.* #send everything that isn't /i to main.app(which is within python)
  script: main.app
  secure: always

